/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    createNativeInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNIDemo_createNativeInstance
  (JNIEnv *, jobject);

/*
 * Class:     JNIDemo
 * Method:    nativeMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIDemo_nativeMethod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNIDemo
 * Method:    destroyNativeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNIDemo_destroyNativeInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNIDemo
 * Method:    HelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_HelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
